- name: Create multiple local users
  hosts: all
  vars_files:
    - users_var.yml
  tasks:
  - name: Add webadmin group
    group:
      name: webadmin
      state: present
  - name: Create user accounts
    win_user:
      name: "{{ item.username }}"
      groups: "{{ item.groups }}"
    loop: "{{ users }}"
