- hosts: all
  tasks:
  - debug:
      var: ansible_facts["all_ipv4_addresses"]|type_debug
  - debug:
      var: ansible_facts["memory_mb"]|type_debug
  - debug:
      var: ansible_facts["machine"]|type_debug
